name: CI

on:
  push:
    branches: [main]
    branches: [ work ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'


      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install Node dependencies
        run: |
          if [ -f package.json ]; then npm install; fi

      - name: Run Python tests
        run: |
          if [ -d tests ]; then
            pytest --cov=./ --cov-report=xml
          else
            echo 'No tests found'
            mkdir -p coverage
            echo '<?xml version="1.0" ?><coverage></coverage>' > coverage.xml
          fi

      - name: Run Node tests
        run: |
          if [ -f package.json ]; then
            npm test -- --coverage
          else
            echo 'No package.json found'
            mkdir -p coverage
            echo 'TN:' > coverage/lcov.info
          fi

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: |
            coverage.xml
            coverage/lcov.info

      - name: Run tests
        run: python -m unittest discover -s tests -v
